services:
  rmi-ns:
      container_name: rmi-ns
      build: pyro
      network_mode: host

  database-server:
    container_name: server-db
    build: server-db
    volumes:
      - ./server-db:/usr/local/ccf355/server-db
    working_dir: /usr/local/ccf355/server-db
    network_mode: host

  application-server:
    container_name: server-app
    build: server-app
    volumes:
      - ./server-app:/usr/local/ccf355/server-app
    working_dir: /usr/local/ccf355/server-app
    network_mode: host

  client-jogador1:
    container_name: client-jogador1
    build: client
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/usr/local/ccf355/client
    working_dir: /usr/local/ccf355/client
    network_mode: host

  client-jogador2:
    container_name: client-jogador2
    build: client
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/usr/local/ccf355/client
    working_dir: /usr/local/ccf355/client
    network_mode: host

  client-jogador3:
      container_name: client-jogador3
      build: client
      environment:
        - DISPLAY=$DISPLAY
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./client:/usr/local/ccf355/client
      working_dir: /usr/local/ccf355/client
      network_mode: host